-- 1
CREATE TABLE MY_MEMBER (
	MEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MEM_ID VARCHAR(50) NOT NULL UNIQUE
	, MEM_PW VARCHAR(100) NOT NULL
	, MEM_NAME VARCHAR(50) NOT NULL
	, MEM_AGE INT 
	, MEM_EMAIL VARCHAR(100)
);

-- 2
INSERT INTO MY_MEMBER (
	MEM_ID,MEM_PW,MEM_NAME,MEM_AGE,MEM_EMAIL
) VALUES (
	'abc','a123','김철수',30,'a123@gmail.com00'
);

DELETE FROM MY_MEMBER;

-- 3
UPDATE MY_MEMBER
SET MEM_NAME='김자바',MEM_ID='KIMJAVA'
WHERE MEM_NUM=1;

-- 4
SELECT EMPNO,ENAME,SAL,COMM
FROM emp
WHERE SAL<3000
AND SAL>500
AND COMM!=NULL;

-- 5
SELECT EMPNO,ENAME,HIREDATE
FROM emp
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;


-- 6
SELECT EMPNO,ENAME,DEPTNO,
(CASE
WHEN DEPTNO=10 THEN '인사부'
WHEN DEPTNO=20 THEN '영업부'
WHEN DEPTNO=30 THEN '개발부'
ELSE '생산부' END) AS DNAME
FROM emp; 


-- 7 
SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM,0)
FROM emp
WHERE MONTH(HIREDATE)=1
ORDER BY HIREDATE;


-- 8 
SELECT SUM(SAL) AS 급여합,AVG(SAL) AS 급여평균, AVG(COMM) AS 커미션평균
FROM emp
GROUP BY DEPTNO
ORDER BY SUM(SAL) DESC;


-- 9
SELECT ENAME, EMPNO, HIREDATE, SAL, DEPTNO,
(SELECT DNAME 
FROM dept 
WHERE dept.DEPTNO=emp.DEPTNO)
AS DNAME
FROM emp
WHERE (
SELECT DNAME
FROM dept
WHERE dept.DEPTNO=emp.DEPTNO)='인사부';

-- 10
SELECT EMPNO, ENAME, HIREDATE, SAL, E.DEPTNO, DNAME
FROM emp E, dept D 
WHERE DNAME!='인사부'
AND SAL >= 500
AND D.DEPTNO = E.DEPTNO
ORDER BY DEPTNO DESC, ENAME;
