CREATE TABLE CAR_INFO (
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT
	,MODEL_NAME VARCHAR(50) NOT NULL
	,PRICE INT NOT NULL
	,MAKE VARCHAR(50) NOT NULL
);

CREATE TABLE SALES_INFO (
	SELL_NUM INT PRIMARY KEY AUTO_INCREMENT
	,SELLER_NAME VARCHAR(50) NOT NULL
	,SELLER_TEL VARCHAR(50)
	,COLOR VARCHAR(50) NOT NULL
	,SELL_DATE DATE DEFAULT CURRENT_TIMESTAMP
	,MODEL_NUM INT NOT NULL REFERENCES CAR_INFO (MODEL_NUM)
);

SELECT * FROM CAR_INFO;
SELECT * FROM sales_info;

UPDATE sales_info
SET COLOR='블랙'
WHERE SELL_NUM=2;

DELETE FROM car_info WHERE MODEL_NUM=9;

INSERT INTO car_info (
	MODEL_NAME
	,PRICE
	,MAKE
) VALUES (
	'제네시스 gv70'
	,6230
	,'현대'
);

DROP TABLE SALES_INFO;
DROP TABLE CAR_INFO;

