-- 리액트에서 기본 게시판 프로젝트 

CREATE TABLE REACT_BOARD (
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BOARD_TITLE VARCHAR(50) NOT NULL
	, BOARD_CONTENT VARCHAR(100)
	, BOARD_WRITER VARCHAR(30) NOT NULL
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);


SELECT * FROM REACT_BOARD;

INSERT INTO REACT_BOARD (
	BOARD_TITLE
	, BOARD_WRITER
	, BOARD_CONTENT
) VALUES (
	'그래 내가 개다'
	,	'월'
	,	'그래 내가 세다 월'
);


CREATE TABLE REACT_STUDENT (
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
	, STU_NAME VARCHAR(30) NOT NULL
	, KOR_SCORE INT
	, ENG_SCORE INT
	, MATH_SCORE INT
	, STU_AGE INT 
	, STU_TEL VARCHAR(20) UNIQUE
	, STU_ADDR VARCHAR(50)
);

CREATE TABLE react_student2 (
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
	, STU_NAME VARCHAR(30) NOT NULL
	, KOR_SCORE INT
	, ENG_SCORE INT
	, MATH_SCORE INT
	, STU_AGE INT 
	, STU_TEL VARCHAR(20) UNIQUE
	, STU_ADDR VARCHAR(50)
);

SELECT * FROM react_student2;

SELECT STU_NUM
      ,STU_NAME
      ,KOR_SCORE
      ,ENG_SCORE
      ,MATH_SCORE
      ,(KOR_SCORE+ENG_SCORE+MATH_SCORE)/3 AS AVG
FROM react_student;

INSERT INTO REACT_STUDENT (
	STU_NAME
	, KOR_SCORE
	, ENG_SCORE
	, MATH_SCORE
) VALUES (
	'김수한무'
	, 20
	, 30
	, 40
);


CREATE TABLE ITEM_INFO (
 ITEM_NUM INT AUTO_INCREMENT PRIMARY KEY-- 상품번호
, ITEM_NAME VARCHAR(50) NOT NULL-- 상품명
, ITEM_PRICE INT NOT NULL-- 상품가격
, SELLER VARCHAR(30) NOT NULL-- 판매자
, ITEM_INTRO VARCHAR(100)-- 상품 설명
, REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 );
 
 SELECT * FROM ITEM_INFO;
 
 CREATE TABLE ORDER_INFO (
 ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY-- 주문번호
, BUY_ITEM_NAME VARCHAR(50)-- 구매 상품명
, BUY_ITEM_PRICE INT-- 구매 상품 단가
, BUYER VARCHAR(50) NOT NULL-- 구매자
, BUY_CNT INT-- 구매 수량
, BUY_PRICE INT-- 구매 가격 (단가 * 수량)
 , BUY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 );
 
 SELECT * FROM ORDER_INFO;