

-- VIEW 
-- 가상 테이블
-- VIEW 사용 이유
-- 1. 민감한 데이터를 보안하기 위해 (숨기기 위해서)
-- 2. 잦은 조인, 서브쿼리 작성에 대한 피로감을 줄이기 위해 
SELECT * FROM emp;

-- VIEW (가상 테이블 - 테이블처럼 사용)
-- VIEW 생성 
CREATE VIEW EMP_VIEW AS
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM emp;

-- VIEW 생성 후 조회문은 테이블과 동일 
SELECT * FROM EMP_VIEW; 


SELECT * FROM join_stu;

CREATE VIEW STU_VIEW AS
SELECT STU_NUM,STU_NAME
FROM join_stu;

SELECT * FROM STU_VIEW;

SELECT * FROM STU_VIEW
WHERE STU_NUM>2;


CREATE VIEW STU_VIEW_2 AS 
SELECT STU_NUM S_NUM, STU_NAME S_NAME
FROM join_stu
WHERE STU_NUM<4;

SELECT S_NUM FROM STU_VIEW_2;


CREATE VIEW STU_SCORE_VIEW AS
SELECT STU.STU_NUM, STU_NAME, SCORE
FROM join_stu STU JOIN join_score SCORE
ON STU.STU_NUM=SCORE.STU_NUM;

SELECT * FROM STU_SCORE_VIEW
WHERE SCORE>70;


DROP VIEW STU_SCORE_VIEW;



